name: p_l
channels:
  - conda-forge
dependencies:
  - espaloma = 0.3.2
  - flowermd
  - fresnel >=0.13.5
  - freud >= 3.0
  - gmso <=0.12.4
  - grits >= 0.5.1
  - gsd >=3.0
  - hoomd >=4.0
  - jupyter
  - matplotlib
  - mbuild >=0.16.4
  - mdanalysis
  - numpy
  - openbabel
  - pip
  - py3Dmol
  - python >= 3.10,<3.12
  - rdkit
  - signac <= 1.8
  - signac-flow <= 0.24
  - statsmodel
