name: p_l
channels:
  - conda-forge
dependencies:
  - freud >= 3.0
  - gmso >=0.11.2
  - fresnel >=0.13.5
  - gsd >=3.0
  - hoomd >=4.0
  - mbuild >=0.16.4
  - numpy
  - pip
  - python >= 3.10,<3.12
  - matplotlib
  - mdanalysis
  - jupyter
  - espaloma = 0.3.2
  - grits >=0.5.0
  - openbabel
  - py3Dmol
  - flowermd
  - signac <= 1.8
  - signac-flow <= 0.24